config/routes.rb
Rails.application.routes.draw do
  root 'surveysets#index'
  get 'static_pages/home'
  get 'static_pages/help'
  get  '/secretsignup',  to: 'users#new'
  resources :surveysets
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/surveyset.rb
class Surveyset < ApplicationRecord
  belongs_to :user, required: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :surveysets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/surveysets_controller.rb
class SurveysetsController < ApplicationController
  before_action :set_surveyset, only: [:show, :edit, :update, :destroy]

  # GET /surveysets
  # GET /surveysets.json
  def index
    @surveysets = Surveyset.all
  end

  # GET /surveysets/1
  # GET /surveysets/1.json
  def show
  end

  # GET /surveysets/new
  def new
    @surveyset = Surveyset.new
  end

  # GET /surveysets/1/edit
  def edit
  end

  # POST /surveysets
  # POST /surveysets.json
  def create
    @surveyset = Surveyset.new(surveyset_params)

    respond_to do |format|
      if @surveyset.save
        format.html { redirect_to @surveyset, notice: 'Surveyset was successfully created.' }
        format.json { render :show, status: :created, location: @surveyset }
      else
        format.html { render :new }
        format.json { render json: @surveyset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveysets/1
  # PATCH/PUT /surveysets/1.json
  def update
    respond_to do |format|
      if @surveyset.update(surveyset_params)
        format.html { redirect_to @surveyset, notice: 'Surveyset was successfully updated.' }
        format.json { render :show, status: :ok, location: @surveyset }
      else
        format.html { render :edit }
        format.json { render json: @surveyset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveysets/1
  # DELETE /surveysets/1.json
  def destroy
    @surveyset.destroy
    respond_to do |format|
      format.html { redirect_to surveysets_url, notice: 'Surveyset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surveyset
      @surveyset = Surveyset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surveyset_params
      params.require(:surveyset).permit(:name, :full_name, :category, :description, :license, :fees, :intervals, :scoring, :link_to_questions, :user_id, :number_of_questions, :time_to_complete, :completion_rate, :condition_type, :care_plans)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :user_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveysets_helper.rb
module SurveysetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",  'http://healthloop.com/about/' %></li>
      <li><%= link_to "Contact", 'http://healthloop.com/contact-us/' %></li>
      <li><%= link_to "News", 'http://healthloop.com/press/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="top-nav navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <!-- <%= link_to "healthloop.png", "healthloop.png", id: "logo" %> -->
        <%= image_tag("healthloop.png", :alt => "HealthLoop", :id => "hl_logo") %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Log in", '#' %></li> -->
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',  'data-turbolinks-track': 'reload'%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HL</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help Page </title>
  </head>
  <body>
    <h1>Help page</h1>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>HealthLoop PROMs library</h1>

  <h2>
    This is the home page for the
    <a href="http://healthloop.com/">HealthLoop</a>
    PROMs library.
    test
  </h2>
</div>

app/views/surveysets/_form.html.erb
<%= form_for(surveyset) do |f| %>
  <% if surveyset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(surveyset.errors.count, "error") %> prohibited this surveyset from being saved:</h2>

      <ul>
      <% surveyset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :license %>
    <%= f.text_area :license %>
  </div>

  <div class="field">
    <%= f.label :fees %>
    <%= f.text_area :fees %>
  </div>

  <div class="field">
    <%= f.label :intervals %>
    <%= f.text_area :intervals %>
  </div>

  <div class="field">
    <%= f.label :scoring %>
    <%= f.text_area :scoring %>
  </div>

  <div class="field">
    <%= f.label :link_to_questions %>
    <%= f.text_area :link_to_questions %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :number_of_questions %>
    <%= f.text_field :number_of_questions %>
  </div>

  <div class="field">
    <%= f.label :time_to_complete %>
    <%= f.text_field :time_to_complete %>
  </div>

  <div class="field">
    <%= f.label :completion_rate %>
    <%= f.text_field :completion_rate %>
  </div>

  <div class="field">
    <%= f.label :condition_type %>
    <%= f.text_area :condition_type %>
  </div>

  <div class="field">
    <%= f.label :care_plans %>
    <%= f.text_area :care_plans %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveysets/edit.html.erb
<h1>Editing Surveyset</h1>

<%= render 'form', surveyset: @surveyset %>

<%= link_to 'Show', @surveyset %> |
<%= link_to 'Back', surveysets_path %>

app/views/surveysets/index.html.erb
<div class="center">
  <h1>
    HealthLoop PROMs Library
  </h1>

</div>

<!-- Filters -->
<section id="choose">
  <h4 id="filter_instruction">
    Filter from <%= Surveyset.count %> PROMs by clicking on the below
  </h4>



  <div class="categories">
    <% Surveyset.distinct(:category).order(:category).pluck(:category).each do |category| %>
        <span class="filters"><%= category %></span>
    <% end %>
  </div>
  <div id="clear_filter">Clear Filter</div>



</section>


<div class="clear"></div>

  <div class="surveysets">
    <% @surveysets.order(:name).each do |surveyset| %>


        <div class="prom">
          <span class="prom_name"><%= surveyset.name %> </span>
          <span class="small_category"><%= surveyset.category %> </span>
          <br>
          <a href="#" class="expand">Show more</a>

          <section class="more_info">
            <table>
              <head>
                <title>HTML Tables</title>
              </head>
              <body>
              <tr>
                <td id="license">
                    <span class="teeny">License Required: </span>
                    <%= surveyset.license %>
                </td>
                <td id="number_of_questions">
                    <span class="teeny"># of Questions: </span>
                    <%= surveyset.number_of_questions %>
                </td>
                <td id="completion_rate">
                  <span class="teeny">Completion Time: </span>
                    <%= surveyset.time_to_complete %>
                </td>
              </tr>
            </table>

            <p id="full_name" class="box">
              <span class="biggish">Full Name</span><br>
              <%= surveyset.full_name %>
            </p>

            <p id="description" class="box">
              <span class="biggish">Description</span><br>
              <%= surveyset.description %>
            </p>

            <p id="fees" class="box">
              <span class="biggish">Fees</span><br>
              <%= surveyset.fees %>
            </p>

            <p id="intervals" class="box">
              <span class="biggish">Intervals</span><br>
              <%= surveyset.intervals %>
            </p>

            <p id="scoring" class="box">
              <span class="biggish">Scoring</span><br>
              <%= surveyset.scoring %>
            </p>

            <p id="completion_rate" class="box">
              <span class="biggish">Completion Requirements for Scoring</span><br>
              <%= surveyset.completion_rate %>
            </p>

            <p id="condition_type" class="box">
              <span class="biggish">Procedure or Conditions</span><br>
              <%= surveyset.condition_type %>
            </p>

            <!-- <p id="care_plans" class="box">
              Care Plans: <%= surveyset.care_plans %>
            </p> -->

            <p id="link_to_questions" class="btn-primary btn">
              <a href=<%= surveyset.link_to_questions %> target = "_blank">SEE QUESTIONS</a>
            </p>

          </section>

        </div>

        <!-- HIDE
        <td><%= link_to 'Show', surveyset %></td>
        <td><%= link_to 'Edit', edit_surveyset_path(surveyset) %></td>
        <td><%= link_to 'Destroy', surveyset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%= link_to 'New Surveyset', new_surveyset_path %> -->
      </div>
    <% end %>

app/views/surveysets/new.html.erb
<h1>New Surveyset</h1>

<%= render 'form', surveyset: @surveyset %>

<%= link_to 'Back', surveysets_path %>

app/views/surveysets/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @surveyset.name %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @surveyset.full_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @surveyset.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @surveyset.description %>
</p>

<p>
  <strong>License:</strong>
  <%= @surveyset.license %>
</p>

<p>
  <strong>Fees:</strong>
  <%= @surveyset.fees %>
</p>

<p>
  <strong>Intervals:</strong>
  <%= @surveyset.intervals %>
</p>

<p>
  <strong>Scoring:</strong>
  <%= @surveyset.scoring %>
</p>

<p>
  <strong>Link to questions:</strong>
  <%= @surveyset.link_to_questions %>
</p>


<p>
  <strong>Number of questions:</strong>
  <%= @surveyset.number_of_questions %>
</p>

<p>
  <strong>Time to complete:</strong>
  <%= @surveyset.time_to_complete %>
</p>

<p>
  <strong>Completion rate:</strong>
  <%= @surveyset.completion_rate %>
</p>

<p>
  <strong>Condition type:</strong>
  <%= @surveyset.condition_type %>
</p>

<p>
  <strong>Care plans:</strong>
  <%= @surveyset.care_plans %>
</p>

<p>
  <strong>User:</strong>
  <%= @surveyset.user_id %>
</p>

<%= link_to 'Edit', edit_surveyset_path(@surveyset) %> |
<%= link_to 'Back', surveysets_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :user_type %>
    <%= f.text_field :user_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>User Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.user_type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>